-- MySQL Script generated by MySQL Workbench
-- seg 13 mai 2019 11:21:18 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  `FormaPagamento` VARCHAR(45) NOT NULL,
  `dataValidadeCartao` DATE NOT NULL,
  `frete` VARCHAR(45) NOT NULL,
  `NumeroCartao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPagamento`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC),
  UNIQUE INDEX `NumeroCartao_UNIQUE` (`NumeroCartao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NULL,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `dataFabricacao` DATE NOT NULL,
  `dataValidade` DATE NOT NULL,
  `fabricante` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrinho` (
  `idCarrinho` INT NOT NULL AUTO_INCREMENT,
  `numeroItens` INT NULL,
  `valorAtual` FLOAT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`idCarrinho`),
  INDEX `fk_Carrinho_Pagamento1_idx` (`Pagamento_idPagamento` ASC),
  INDEX `fk_Carrinho_Produto1_idx` (`Produto_idProduto` ASC),
  UNIQUE INDEX `idCarrinho_UNIQUE` (`idCarrinho` ASC),
  CONSTRAINT `fk_Carrinho_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrinho_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `CPF` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `PrimeiroNome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `País` VARCHAR(45) NULL,
  `Rua` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `NumeroResidencial` INT NULL,
  `DataNascimento` DATE NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `Carrinho_idCarrinho1` INT NOT NULL,
  INDEX `fk_Cliente_Carrinho1_idx` (`Carrinho_idCarrinho1` ASC),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC),
  CONSTRAINT `fk_Cliente_Carrinho1`
    FOREIGN KEY (`Carrinho_idCarrinho1`)
    REFERENCES `mydb`.`Carrinho` (`idCarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
